version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/cache"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/derive_lazy_playlist_child"
    schedule:
      interval: "weekly"
